/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 floor.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Floor(props) {
  const { nodes, materials } = useGLTF('./models/floor.gltf')
  return (
    <group {...props} dispose={null} castShadows receiveShadow scale={0.05} rotation={[Math.PI / -2, 0, 0]}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('./models/floor.gltf')

export default Floor
