/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ElfDragonPaladin_000.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Paladin(props) {
  const { nodes, materials } = useGLTF('./models/ElfDragonPaladin_000.glb')
  return (
    <group {...props} dispose={null} scale={0.05} rotation={[Math.PI / -2, 0, 0]}>
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('./models/ElfDragonPaladin_000.glb')

export default Paladin;
